import "@/styles/globals.css";

import { Montserrat } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";

import Nav from "./_components/Nav";
import Header from "./_components/Header";

const montserrat = Montserrat({
  weight: "500",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} flex-col font-mono`}>
        <div className="flex flex-row">
          <Nav />
          <Header />
        </div>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
